import json
import sqlite3
import threading
import time
from flask import Flask, jsonify, render_template_string, request
import requests

app = Flask(__name__)

last_sequence_id = None

# =========================================================
# SIMULATOR & AUTH SETTINGS
# =========================================================

SIMULATOR_BASE_URL = "http://127.0.0.1:9898/api/v1" 

# The token generated by your friend in Bruno
JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbiIsImV4cCI6MTc5MDA2NTUxMywiaXNzIjoiUGFya2luZ1NpbXVsYXRvciJ9.Td2Fo0AyYU2bUw_jUkJZ4VEfY9E9b_mHFN_zwrDku10"

ENTRY_GATE_NAME = "gateA"
EXIT_GATE_NAME = "gateB"

# Parking spots ordered strictly by proximity/distance tier
PARK_SPOTS = [
    # Tier 1 (Closest)
    "S1", "S2", "S3", "S4", "S5",
    "S16", "S17", "S18", "S19", "S20",
    # Tier 2 (Middle)
    "S6", "S7", "S8", "S9", "S10",
    "S21", "S22", "S23", "S24", "S25",
    # Tier 3 (Farthest)
    "S11", "S12", "S13", "S14", "S15",
    "S26", "S27", "S28", "S29", "S30",
]

# State tracking for occupied spots and duration analytics
spot_lock = threading.Lock()
spot_state = {}

duration_lock = threading.Lock()
car_entry_times = {}       # plate -> timestamp (float)
completed_durations = []   # list of total stay times (in seconds)
total_revenue = 0.0        # total money collected


# =========================================================
# API HELPER FUNCTIONS WITH AUTH
# =========================================================


def get_headers():
    return {
        "Authorization": f"Bearer {JWT_TOKEN}",
        "Content-Type": "application/json",
    }


def open_barrier_gate(gate_name):
    """Sends request to open barrier gate."""
    url = f"{SIMULATOR_BASE_URL}/barrier-gates/{gate_name}/open"
    try:
        response = requests.post(url, headers=get_headers(), timeout=2)
        print(f"OPEN GATE ({gate_name}): HTTP {response.status_code}")
    except requests.RequestException as e:
        print(f"Error opening gate {gate_name}:", e)


def close_barrier_gate(gate_name):
    """Sends request to close barrier gate."""
    url = f"{SIMULATOR_BASE_URL}/barrier-gates/{gate_name}/close"
    try:
        response = requests.post(url, headers=get_headers(), timeout=2)
        print(f"CLOSE GATE ({gate_name}): HTTP {response.status_code}")
    except requests.RequestException as e:
        print(f"Error closing gate {gate_name}:", e)


def initialize_gates():
    """Forces all gates to start in a closed state to prevent them from being left open."""
    print("Initializing gates to CLOSED state...")
    close_barrier_gate(ENTRY_GATE_NAME)
    close_barrier_gate(EXIT_GATE_NAME)


def charge_car_and_open_exit(plate, car_type):
    """Calculates fee, bills the car, opens the exit gate, and uses rapid-fire to guarantee instant exit."""
    global total_revenue
    
    with duration_lock:
        entry_time = car_entry_times.get(plate, time.time() - 60)
        
    duration_sec = time.time() - entry_time
    minutes_spent = max(1, int(duration_sec / 60))

    parking_cost = float(minutes_spent)
    charging_cost = float(minutes_spent) if car_type == "Electric" else 0.0
    total_bill = parking_cost + charging_cost

    with duration_lock:
        total_revenue += total_bill

    charge_url = f"{SIMULATOR_BASE_URL}/car/{plate}/charge?parkingCost={parking_cost}&chargingCost={charging_cost}"
    
    try:
        requests.post(charge_url, headers=get_headers(), timeout=2)
        print(f"CHARGE CAR {plate} Total: ${total_bill} (Park: {parking_cost}, Charge: {charging_cost})")
        
        open_barrier_gate(EXIT_GATE_NAME)
        
        leave_url = f"{SIMULATOR_BASE_URL}/car/{plate}/goto/leavepark"
        
        # RAPID-FIRE EXIT LOGIC
        # Spams the move command every 0.1 seconds so the car moves the instant the gate allows it
        for _ in range(15):
            try:
                requests.post(leave_url, headers=get_headers(), timeout=1)
            except:
                pass
            time.sleep(0.1)

    except requests.RequestException as e:
        print(f"Error during exit sequence for car {plate}:", e)


# =========================================================
# DATABASE SETUP & HELPERS
# =========================================================


def init_database():
    connection = sqlite3.connect("parking.db")
    cursor = connection.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS webhook_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event_id TEXT UNIQUE,
            sequence_id INTEGER,
            event_class TEXT,
            car_plate TEXT,
            car_type TEXT,
            spot_name TEXT,
            spot_type TEXT,
            direction TEXT,
            amount TEXT,
            reason TEXT,
            server_datetime TEXT,
            raw_data TEXT
        )
    """)
    connection.commit()
    connection.close()


def event_already_exists(event_id):
    if event_id is None:
        return False
    connection = sqlite3.connect("parking.db")
    cursor = connection.cursor()
    cursor.execute(
        "SELECT event_id FROM webhook_events WHERE event_id = ?", (event_id,)
    )
    result = cursor.fetchone()
    connection.close()
    return result is not None


def save_event(data):
    connection = sqlite3.connect("parking.db")
    cursor = connection.cursor()
    cursor.execute(
        """
        INSERT INTO webhook_events (
            event_id, sequence_id, event_class, car_plate, car_type,
            spot_name, spot_type, direction, amount, reason,
            server_datetime, raw_data
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """,
        (
            data.get("EventId"),
            data.get("SequenceId"),
            data.get("EventClass"),
            data.get("CarPlateNumber"),
            data.get("CarType"),
            data.get("SpotName"),
            data.get("SpotType"),
            data.get("Direction"),
            data.get("Amount"),
            data.get("Reason"),
            data.get("ServerDateTime"),
            json.dumps(data),
        ),
    )
    connection.commit()
    connection.close()


def get_recent_events():
    connection = sqlite3.connect("parking.db")
    connection.row_factory = sqlite3.Row
    cursor = connection.cursor()
    cursor.execute("""
        SELECT id, sequence_id, event_class, car_plate, car_type,
               spot_name, spot_type, direction, amount, reason, server_datetime
        FROM webhook_events ORDER BY id DESC LIMIT 100
    """)
    events = cursor.fetchall()
    connection.close()
    return events


# =========================================================
# AUTO-PARK LOGIC
# =========================================================


def reserve_free_spot(plate):
    with spot_lock:
        for spot in PARK_SPOTS:
            if spot not in spot_state:
                spot_state[spot] = plate
                return spot
    return None


def release_spot(spot_name):
    with spot_lock:
        spot_state.pop(spot_name, None)


def auto_park_car(plate, entry_spot):
    spot = reserve_free_spot(plate)
    if spot is None:
        print(f"NO FREE SPOT for {plate}")
        return

    open_barrier_gate(ENTRY_GATE_NAME)
    url = f"{SIMULATOR_BASE_URL}/car/{plate}/goto/{spot}"

    # RAPID-FIRE ENTRY LOGIC
    # Spams the move command 15 times so the car enters instantly regardless of GlobalSpeed
    for _ in range(15):
        try:
            requests.post(url, headers=get_headers(), timeout=1)
        except:
            pass
        time.sleep(0.1)


# =========================================================
# FLASK ROUTES
# =========================================================


@app.route("/", methods=["GET"])
def home():
    return """
        <h1>NextGen Parking Webhook</h1>
        <p>Webhook server is ONLINE.</p>
        <p><a href="/events">View Stored Events</a></p>
    """


@app.route("/events", methods=["GET"])
def events_page():
    events = get_recent_events()
    
    with duration_lock:
        total_cars = len(completed_durations)
        current_revenue = total_revenue
        if total_cars > 0:
            avg_sec = sum(completed_durations) / total_cars
            if avg_sec < 60:
                avg_duration = f"{avg_sec:.0f} seconds"
            else:
                avg_duration = f"{avg_sec / 60:.1f} minutes"
        else:
            avg_duration = "N/A"

    page = """
    <!DOCTYPE html>
    <html>
    <meta http-equiv="refresh" content="1">
    <head>
        <title>NextGen Parking Events</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 30px; background-color: #f5f5f5; }
            .stats-card { background-color: white; padding: 20px; border: 1px solid #dddddd; border-left: 5px solid #222; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
            .stats-card h2 { margin-top: 0; font-size: 1.2rem; color: #333; }
            .stats-data { display: flex; gap: 40px; }
            .stat-item { display: flex; flex-direction: column; }
            .stat-value { font-size: 1.5rem; font-weight: bold; color: #222; }
            .stat-value.money { color: #2e7d32; }
            .stat-label { font-size: 0.9rem; color: #666; }
            table { width: 100%; border-collapse: collapse; background-color: white; }
            th, td { border: 1px solid #dddddd; padding: 10px; text-align: left; }
            th { background-color: #222222; color: white; }
            tr:nth-child(even) { background-color: #eeeeee; }
        </style>
    </head>
    <body>
        <h1>NextGen Parking Event Log</h1>
        
        <div class="stats-card">
            <h2>Car Park Statistics (Current Session)</h2>
            <div class="stats-data">
                <div class="stat-item">
                    <span class="stat-value money">${{ "%.2f"|format(current_revenue) }}</span>
                    <span class="stat-label">Total Revenue</span>
                </div>
                <div class="stat-item">
                    <span class="stat-value">{{ avg_duration }}</span>
                    <span class="stat-label">Average Stay Duration</span>
                </div>
                <div class="stat-item">
                    <span class="stat-value">{{ total_cars }}</span>
                    <span class="stat-label">Total Cars Completed</span>
                </div>
            </div>
        </div>

        <table>
            <tr>
                <th>ID</th><th>Sequence</th><th>Event</th><th>Car Plate</th>
                <th>Car Type</th><th>Spot</th><th>Spot Type</th><th>Direction</th>
                <th>Amount</th><th>Reason</th><th>Time</th>
            </tr>
            {% for event in events %}
            <tr>
                <td>{{ event["id"] }}</td>
                <td>{{ event["sequence_id"] or "-" }}</td>
                <td>{{ event["event_class"] or "-" }}</td>
                <td>{{ event["car_plate"] or "-" }}</td>
                <td>{{ event["car_type"] or "-" }}</td>
                <td>{{ event["spot_name"] or "-" }}</td>
                <td>{{ event["spot_type"] or "-" }}</td>
                <td>{{ event["direction"] or "-" }}</td>
                <td>{{ event["amount"] or "-" }}</td>
                <td>{{ event["reason"] or "-" }}</td>
                <td>{{ event["server_datetime"] or "-" }}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
    </html>
    """
    return render_template_string(page, events=events, avg_duration=avg_duration, total_cars=total_cars, current_revenue=current_revenue)


@app.route("/webhook", methods=["POST"])
def receive_webhook():
    global last_sequence_id
    data = request.get_json(silent=True)

    if data is None:
        return jsonify({"status": "invalid json"}), 400

    event_id = data.get("EventId")
    sequence_id = data.get("SequenceId")
    event_class = data.get("EventClass")

    if event_already_exists(event_id):
        return jsonify({"status": "duplicate ignored"}), 200

    if sequence_id is not None:
        if last_sequence_id is not None and sequence_id != last_sequence_id + 1:
            print(f"WARNING: Sequence gap! Expected {last_sequence_id + 1}, got {sequence_id}")
        last_sequence_id = sequence_id

    try:
        save_event(data)
    except Exception as error:
        print("DATABASE ERROR:", error)

    # Handlers
    if event_class == "car_spot_action":
        plate = data.get("CarPlateNumber")
        car_type = data.get("CarType")
        spot_name = data.get("SpotName")
        spot_type = data.get("SpotType")
        direction = data.get("Direction")

        # --- ENTRY LOGIC ---
        if spot_type == "EntrySpot" and direction == "CarIn":
            print(f"NEW CAR ARRIVED: {plate}")
            with duration_lock:
                car_entry_times[plate] = time.time()
            threading.Thread(
                target=auto_park_car, args=(plate, spot_name), daemon=True
            ).start()

        elif spot_type == "EntrySpot" and direction == "CarOut":
            print(f"CAR PASSED ENTRY: {plate}. Closing Gate...")
            threading.Thread(
                target=close_barrier_gate, args=(ENTRY_GATE_NAME,), daemon=True
            ).start()

        # --- PARKING LOGIC ---
        elif spot_type == "Park" and direction == "CarIn":
            print(f"CAR PARKED: {plate} at {spot_name}")
            with spot_lock:
                spot_state[spot_name] = plate

        elif spot_type == "Park" and direction == "CarOut":
            print(f"CAR LEFT SPOT: {plate} from {spot_name}")
            release_spot(spot_name)

        # --- EXIT LOGIC ---
        elif spot_type == "ExitSpot" and direction == "CarIn":
            print(f"CAR ARRIVED AT EXIT: {plate}")
            threading.Thread(
                target=charge_car_and_open_exit, args=(plate, car_type), daemon=True
            ).start()

        elif spot_type == "ExitSpot" and direction == "CarOut":
            print(f"CAR LEFT THE CAR PARK: {plate}. Closing Gate...")
            
            with duration_lock:
                if plate in car_entry_times:
                    duration_sec = time.time() - car_entry_times[plate]
                    completed_durations.append(duration_sec)
                    del car_entry_times[plate]

            threading.Thread(
                target=close_barrier_gate, args=(EXIT_GATE_NAME,), daemon=True
            ).start()

    return jsonify({"status": "received"}), 200


if __name__ == "__main__":
    init_database()
    initialize_gates() 
    app.run(host="0.0.0.0", port=5000, debug=True, use_reloader=False)